/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bardaesquina;

import java.awt.Color;
import java.awt.Container;
import java.util.ArrayList;
import java.util.concurrent.Semaphore;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author estagio2
 */
public class BarView extends javax.swing.JFrame {

    /**
     * Creates new form BarView
     */
    Semaphore controleDeVariaveis = new Semaphore(1, true);
    Semaphore controleDeEntradaDeClientes = new Semaphore(1, true);
    int quantidadeTotalDeCadeiras = 0;
    int actualIndex = 0;
    JFrame isto = this;
    int numeroAtualDeClientes = 0;
    int numeroClientesReal = 0;

    public BarView(){
        initComponents();
    }

    public BarView(String barClub, int qntCadeiras) {
        super(barClub);
        initComponents();
        String[] bar = {"/imagens/bar-backgrounds/bar1.png", "/imagens/bar-backgrounds/bar2.png", "/imagens/bar-backgrounds/bar3.png", "/imagens/bar-backgrounds/bar4.png", "/imagens/bar-backgrounds/bar5.png", "/imagens/bar-backgrounds/bar6.png", "/imagens/bar-backgrounds/bar7.png", "/imagens/bar-backgrounds/bar8.png", "/imagens/bar-backgrounds/bar9.png", "/imagens/bar-backgrounds/bar10.png"};
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(bar[qntCadeiras - 1])));
        setSize(1360, 450);
        this.quantidadeTotalDeCadeiras = qntCadeiras;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cliente1 = new javax.swing.JLabel();
        cliente2 = new javax.swing.JLabel();
        cliente3 = new javax.swing.JLabel();
        cliente4 = new javax.swing.JLabel();
        cliente5 = new javax.swing.JLabel();
        cliente6 = new javax.swing.JLabel();
        cliente7 = new javax.swing.JLabel();
        cliente8 = new javax.swing.JLabel();
        cliente9 = new javax.swing.JLabel();
        cliente10 = new javax.swing.JLabel();
        client10 = new javax.swing.JLabel();
        client9 = new javax.swing.JLabel();
        client8 = new javax.swing.JLabel();
        client7 = new javax.swing.JLabel();
        client6 = new javax.swing.JLabel();
        client5 = new javax.swing.JLabel();
        client4 = new javax.swing.JLabel();
        client3 = new javax.swing.JLabel();
        client2 = new javax.swing.JLabel();
        client1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.pink);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Criar bebum");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1090, 313, 250, 100);

        jPanel1.setBackground(new java.awt.Color(41, 41, 41));
        jPanel1.setForeground(new java.awt.Color(0, 255, 0));

        cliente1.setBackground(new java.awt.Color(0, 255, 0));
        cliente1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cliente1.setForeground(new java.awt.Color(0, 255, 0));

        cliente2.setBackground(new java.awt.Color(0, 255, 0));
        cliente2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cliente2.setForeground(new java.awt.Color(0, 255, 0));

        cliente3.setBackground(new java.awt.Color(0, 255, 0));
        cliente3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cliente3.setForeground(new java.awt.Color(0, 255, 0));

        cliente4.setBackground(new java.awt.Color(0, 255, 0));
        cliente4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cliente4.setForeground(new java.awt.Color(0, 255, 0));

        cliente5.setBackground(new java.awt.Color(0, 255, 0));
        cliente5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cliente5.setForeground(new java.awt.Color(0, 255, 0));

        cliente6.setBackground(new java.awt.Color(0, 255, 0));
        cliente6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cliente6.setForeground(new java.awt.Color(0, 255, 0));

        cliente7.setBackground(new java.awt.Color(0, 255, 0));
        cliente7.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cliente7.setForeground(new java.awt.Color(0, 255, 0));

        cliente8.setBackground(new java.awt.Color(0, 255, 0));
        cliente8.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cliente8.setForeground(new java.awt.Color(0, 255, 0));

        cliente9.setBackground(new java.awt.Color(0, 255, 0));
        cliente9.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cliente9.setForeground(new java.awt.Color(0, 255, 0));

        cliente10.setBackground(new java.awt.Color(0, 255, 0));
        cliente10.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        cliente10.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cliente1)
                    .addComponent(cliente2)
                    .addComponent(cliente3)
                    .addComponent(cliente4)
                    .addComponent(cliente5)
                    .addComponent(cliente6)
                    .addComponent(cliente7)
                    .addComponent(cliente8)
                    .addComponent(cliente9)
                    .addComponent(cliente10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cliente1)
                .addGap(6, 6, 6)
                .addComponent(cliente2)
                .addGap(6, 6, 6)
                .addComponent(cliente3)
                .addGap(6, 6, 6)
                .addComponent(cliente4)
                .addGap(6, 6, 6)
                .addComponent(cliente5)
                .addGap(6, 6, 6)
                .addComponent(cliente6)
                .addGap(6, 6, 6)
                .addComponent(cliente7)
                .addGap(6, 6, 6)
                .addComponent(cliente8)
                .addGap(6, 6, 6)
                .addComponent(cliente9)
                .addGap(6, 6, 6)
                .addComponent(cliente10)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1080, 0, 280, 420);

        client10.setBackground(new java.awt.Color(167, 68, 68));
        client10.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        client10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebados/bebado10.png"))); // NOI18N
        client10.setText("Cliente 1");
        getContentPane().add(client10);
        client10.setBounds(980, 300, 100, 100);

        client9.setBackground(new java.awt.Color(167, 68, 68));
        client9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        client9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebados/bebado9.png"))); // NOI18N
        client9.setText("Cliente 1");
        getContentPane().add(client9);
        client9.setBounds(860, 300, 100, 100);

        client8.setBackground(new java.awt.Color(167, 68, 68));
        client8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        client8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebados/bebado8.png"))); // NOI18N
        client8.setText("Cliente 1");
        getContentPane().add(client8);
        client8.setBounds(760, 300, 100, 100);

        client7.setBackground(new java.awt.Color(167, 68, 68));
        client7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        client7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebados/bebado7.png"))); // NOI18N
        client7.setText("Cliente 1");
        getContentPane().add(client7);
        client7.setBounds(650, 300, 100, 100);

        client6.setBackground(new java.awt.Color(167, 68, 68));
        client6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        client6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebados/bebado6.png"))); // NOI18N
        client6.setText("Cliente 1");
        getContentPane().add(client6);
        client6.setBounds(550, 300, 100, 100);

        client5.setBackground(new java.awt.Color(167, 68, 68));
        client5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        client5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebados/bebado5.png"))); // NOI18N
        client5.setText("Cliente 1");
        getContentPane().add(client5);
        client5.setBounds(430, 300, 100, 100);

        client4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebados/bebado4.png"))); // NOI18N
        client4.setText("jLabel4");
        getContentPane().add(client4);
        client4.setBounds(320, 300, 90, 100);

        client3.setBackground(new java.awt.Color(167, 68, 68));
        client3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        client3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebados/bebado3.png"))); // NOI18N
        client3.setText("Cliente 1");
        getContentPane().add(client3);
        client3.setBounds(220, 300, 100, 100);

        client2.setBackground(new java.awt.Color(167, 68, 68));
        client2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        client2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebados/bebado2.png"))); // NOI18N
        client2.setText("Cliente 1");
        getContentPane().add(client2);
        client2.setBounds(110, 300, 100, 100);

        client1.setBackground(new java.awt.Color(167, 68, 68));
        client1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        client1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebados/bebado1.png"))); // NOI18N
        client1.setText("Cliente 1");
        getContentPane().add(client1);
        client1.setBounds(0, 300, 100, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/outros/pista.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 240, 1110, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bar-backgrounds/bar10.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1084, 245);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/outros/casas.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 305, 1080, 120);

        setSize(new java.awt.Dimension(1361, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//       Comente as proximas 10 linhas se quiser adicionar manualmente
//        this.createCliente("Paulo", 5, 10);
//        this.createCliente("Ricardo", 5, 10);
//        this.createCliente("Bernardo", 5, 10);
//        this.createCliente("Nivardo", 5, 10);
//        this.createCliente("João", 5, 10);
//        this.createCliente("Marcus", 5, 10);
//        this.createCliente("Elysson", 5, 10);
//        this.createCliente("Gabriel", 5, 10);
//        this.createCliente("Paulo8", 5, 10);
//        this.createCliente("Paulo9", 5, 10);
//        Descomente a proxima linha se quiser adicionar manualmente
        if(this.actualIndex < 10) {
            new ClienteForm(this).setVisible(true);
        }
            this.cliente1.setText("Cliente 1");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void createCliente(String identificador, float tempoCasa, float tempoBar) {

        ArrayList<JLabel> list = new ArrayList();
        list.add(cliente1);
        list.add(cliente2);
        list.add(cliente3);
        list.add(cliente4);
        list.add(cliente5);
        list.add(cliente6);
        list.add(cliente7);
        list.add(cliente8);
        list.add(cliente9);
        list.add(cliente10);

        ArrayList<JLabel> list1 = new ArrayList();
        list1.add(this.client1);
        list1.add(this.client2);
        list1.add(this.client3);
        list1.add(this.client4);
        list1.add(this.client5);
        list1.add(this.client6);
        list1.add(this.client7);
        list1.add(this.client8);
        list1.add(this.client9);
        list1.add(this.client10);
        this.numeroClientesReal++;
        Cliente cliente = new Cliente(
                this.actualIndex,
                list1.get(this.actualIndex),
                list.get(this.actualIndex++),
                identificador,
                tempoCasa,
                tempoBar,
                controleDeVariaveis,
                controleDeEntradaDeClientes,
                this
        );
        cliente.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel client1;
    public javax.swing.JLabel client10;
    private javax.swing.JLabel client2;
    public javax.swing.JLabel client3;
    private javax.swing.JLabel client4;
    public javax.swing.JLabel client5;
    public javax.swing.JLabel client6;
    public javax.swing.JLabel client7;
    public javax.swing.JLabel client8;
    public javax.swing.JLabel client9;
    private javax.swing.JLabel cliente1;
    private javax.swing.JLabel cliente10;
    private javax.swing.JLabel cliente2;
    private javax.swing.JLabel cliente3;
    private javax.swing.JLabel cliente4;
    private javax.swing.JLabel cliente5;
    private javax.swing.JLabel cliente6;
    private javax.swing.JLabel cliente7;
    private javax.swing.JLabel cliente8;
    private javax.swing.JLabel cliente9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    public JPanel getjPanel2() {
        return jPanel1;
    }

    public void setjPanel2(JPanel jPanel) {
        this.jPanel1 = jPanel;
    }
}
